resources:
  pipelines:
  - pipeline: mysharedrepo   # Name of the pipeline resource
    source: my-shared-repo # Name of the pipeline referenced by the pipeline resource
    trigger: 
      branches:
      - refs/heads/releases/*
      - refs/heads/main

trigger:
- releases/*
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world Test2 Repo!
  displayName: 'Run a one-line script'
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'dev-sonarqube'
    scannerMode: 'MSBuild'
    projectKey: 'be-apigateway'

- task: MSBuild@1
  inputs:
    solution: 'Hello.csproj'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'